services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: jobrunr
      POSTGRES_USER: jobrunr
      POSTGRES_PASSWORD: jobrunr
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: