services:
  mysql:
    image: mysql:8.0
    container_name: path-enum-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: path_enum
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - path-enum-mysql-data:/var/lib/mysql

volumes:
  path-enum-mysql-data:
