package com.example.batch.config

import org.springframework.batch.core.repository.JobRepository
import org.springframework.batch.core.repository.support.JobRepositoryFactoryBean
import org.springframework.batch.support.transaction.ResourcelessTransactionManager
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.jdbc.core.JdbcTemplate
import javax.sql.DataSource

@Configuration
class BatchDataSourceInitializer(
    private val dataSource: DataSource,
    private val jobRepository: JobRepository
) {

    @Bean
    fun initializeSchema(): JdbcTemplate {
        val jdbcTemplate = JdbcTemplate(dataSource)
        
        // Create Spring Batch schema tables
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
                JOB_INSTANCE_ID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                VERSION BIGINT,
                JOB_NAME VARCHAR(100) NOT NULL,
                JOB_KEY VARCHAR(250) NOT NULL,
                constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
            )
        """)
        
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
                JOB_EXECUTION_ID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                VERSION BIGINT,
                JOB_INSTANCE_ID BIGINT NOT NULL,
                CREATE_TIME TIMESTAMP NOT NULL,
                START_TIME TIMESTAMP,
                END_TIME TIMESTAMP,
                STATUS VARCHAR(10),
                EXIT_CODE VARCHAR(20),
                EXIT_MESSAGE VARCHAR(2500),
                LAST_UPDATED TIMESTAMP,
                constraint JOB_EXEC_JOB_INST_FK foreign key (JOB_INSTANCE_ID)
                references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
            )
        """)
        
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
                JOB_EXECUTION_ID BIGINT NOT NULL,
                PARAMETER_NAME VARCHAR(100) NOT NULL,
                PARAMETER_TYPE VARCHAR(100) NOT NULL,
                PARAMETER_VALUE VARCHAR(250),
                IDENTIFYING CHAR(1) NOT NULL,
                constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
            )
        """)
        
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
                STEP_EXECUTION_ID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                VERSION BIGINT,
                STEP_NAME VARCHAR(100) NOT NULL,
                JOB_EXECUTION_ID BIGINT NOT NULL,
                START_TIME TIMESTAMP NOT NULL,
                END_TIME TIMESTAMP,
                STATUS VARCHAR(10),
                COMMIT_COUNT BIGINT,
                READ_COUNT BIGINT,
                FILTER_COUNT BIGINT,
                WRITE_COUNT BIGINT,
                EXIT_CODE VARCHAR(20),
                EXIT_MESSAGE VARCHAR(2500),
                LAST_UPDATED TIMESTAMP,
                constraint STEP_EXEC_JOB_EXEC_FK foreign key (JOB_EXECUTION_ID)
                references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
            )
        """)
        
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
                STEP_EXECUTION_ID BIGINT NOT NULL,
                SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                SERIALIZED_CONTEXT VARCHAR(2500) NOT NULL,
                constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
            )
        """)
        
        return jdbcTemplate
    }
}
